name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout código
         uses: actions/checkout@v4

       - name: Setup Node.js
         uses: actions/setup-node@v4
         with:
          node-version: '18'
          cache: 'npm'

       - name: Instalar dependências
         run: npm ci

       - name: Build da aplicação  
         run: npm run build

       - name: Deploy para Firebase Hosting (Production)
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
         uses: FirebaseExtended/action-hosting-deploy@v0
         with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          projectId: 'seu-project-id-aqui'
          channelId: live
         env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks

       - name: Deploy Preview (Pull Request)
         if: github.event_name == 'pull_request'
         uses: FirebaseExtended/action-hosting-deploy@v0
         with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}'
          projectId: 'seu-project-id-aqui'
         env:
          FIREBASE_CLI_EXPERIMENTS: webframeworks
